### ISSUE TITLE
Visual Studio Project info missing

### ISSUE THREAD

**Issue by leastofthese23** [brminnick/XamList#14]
I was able to follow the read me up until the point of working in VS, then there were no instructions for how to create the project. I thought I might be able to create a blank project and paste in files/code but the images shown in the screenshots show a folder structure that does not match the supplied files. Instructions should be included on creating the project in VS.

**Comment by brminnick** [comment]
You don't need to create a project; the code is all open-source and available to you in the GitHub repo.
