### ISSUE TITLE
Error on .NetFramework

### ISSUE THREAD

**Issue by Ronald-Outlook-com** [brminnick/XamList#16]
I get 8 errors like this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project XamList.Droid is not compatible with net48 (.NETFramework,Version=v4.8) / win-x86. Project XamList.Droid supports: monoandroid11.0 (MonoAndroid,Version=v11.0)	XamList.UITests	C:\Users\RonaldSmid\source\repos\XamList\XamList-main\XamList.UITests\XamList.UITests.csproj	1	

What is the solution?

**Comment by brminnick** [comment]
Thanks @Ronald-Outlook-com.

[Fixed ✅](https://github.com/brminnick/XamList/commit/bc74340426e580218d4055923afc6991325c7112)
